import { I18nContent, Language } from './types';

export const I18N_DATA: Record<Language, I18nContent> = {
  zh: {
    "nav-about": "个人介绍",
    "nav-edu": "教育背景",
    "nav-exp": "经历轴线（含作品集链接）",
    "nav-skills": "技能&特质",
    "nav-cta": "立即联系",
    "hero-sub": "It’s me.",
    "hero-role": "用户洞察 × 创意策略 × 数字体验优化方向候选人",
    "hero-desc": "具备用户研究、内容策划、项目推进与市场分析的复合背景，参与过数字化体验优化、营销研究、内容传播及活动支持等项目，能够在不同场景中完成信息整合、问题拆解与方案输出。\n善于结合 AI 工具与数据洞察，将复杂信息转化为更清晰、高效的用户体验与内容表达，在用户需求、创意表达与实际落地之间建立连接。",
    "edu-hku-major": "悉尼大学（澳大利亚）",
    "edu-hku-desc": "从“做项目”，到“理解问题本身”，是我在研究生阶段最大的变化。\n在悉尼大学的项目管理学习中，我逐渐意识到，项目的本质并不是流程，而是对复杂问题的结构化拆解。无论是成本、风险，还是资源配置，本质上都可以被抽象为数据与决策的关系。\n因此，我开始有意识地引入数据分析与模型思维：\n在增长与内容项目中，通过用户行为拆解与A/B测试，将“感觉”转化为可验证的策略；\n在数字化优化项目中，以数据为依据重构用户路径，让体验改进直接对应转化提升。\n对我来说，AI并不是一个工具集合，而是一种新的问题解决方式——用数据理解世界，用模型逼近决策。",
    "edu-cuhk-major": "上海外国语大学贤达经济人文学院",
    "edu-cuhk-desc": "相比“学了什么”，本科更像是在建立我理解商业世界的底层坐标。\n在本科期间，我从会展与旅游出发，逐步进入更广义的商业语境。无论是一场活动的策划，还是一条旅游线路的设计，本质上都是对“人流、信息与消费决策”组织与引导。\n系统的经济学与管理学训练，让我开始用更结构化的方式理解这些现象：\n从供需关系到用户选择，从成本结构到资源配置，许多原本依赖经验的判断，逐渐可以被拆解与解释。\n在实践中，从大型活动的全流程策划，到用户调研与数据整理，我也逐渐意识到一个关键问题：\n很多“看似成功”的执行，其实缺乏可验证的决策逻辑。\n因此，我开始有意识地从“执行”转向“分析”：\n通过问卷与访谈建立基础数据认知，用统计方法理解用户偏好，并尝试从数据中反推出更稳健的策略方向。\n这段经历让我建立起最初的判断：\n商业的核心，并不只是连接资源，而是理解人在不同情境下的决策机制。",
    "edu-cert-btn": "技能证书",
    "exp-1-t": "AI个人求职网页 · 0-1独立策划与搭建",
    "exp-1-d": " 背景： 在求职过程中，我希望通过一个更直观、更有互动性的个人网页来替代传统静态简历，从而提升个人展示效果，并辅助我与面试官进行更高效的沟通。同时，我也希望借这个项目实践 AI 工具在真实场景中的应用。\n\n 任务： 我的任务是借助 AI 工具，从 0 到 1 独立完成个人求职网页的策划、设计与搭建，并让这个网页不仅能承载个人信息，还能具备更完整的展示与交互功能。\n\n 行动： 在项目推进过程中，我围绕工具选型、页面设计、内容组织、文档整合和部署探索几个方面展开工作。通过不断对比和筛选合适的 AI 工具，我逐步完成了网页结构搭建，并持续优化页面表现与交互方式。同时，解决了图片上传、文档跳转、外部资源整合等具体问题，最终将多个展示需求整合进同一个网页中。\n\n 结果： 最终，我独立完成了一套具备中英文切换、语音欢迎、多版本简历下载、作品集与文档跳转等功能的个人展示网页。这个项目不仅提升了我的个人展示效果，也让我在实践中系统锻炼了 AI 协作、快速学习、问题解决和产品化表达能力。",
    "exp-2-t": "澳洲眼科医院网站体验升级 · 校园合作项目",
    "exp-2-d": "项目总览：\n这是一个为老年视觉护理机构做数字体验升级的项目，目标是围绕预约、登录、信息获取与内部协作流程，找出影响用户使用的关键痛点，并通过问卷、体验评估、原型设计与测试，提出可落地的界面优化方案，从而提升患者、家属、护理机构和医疗人员的使用效率与满意度。\n\n负责内容：\n 梳理预约、登录、首页信息获取及 Dashboard/后台工作台等 4 类关键用户旅程，定位影响任务完成率的核心问题（高跳出率与低挂号转化），并输出优化建议与原型方案。\n\n•  结合问卷、用户反馈与页面流程走查完成问题归因，识别 28.6% 用户在预约入口存在障碍、20% 用户对系统响应速度不满、28.6% 用户不愿推荐网站，为优化优先级提供依据。\n\n•  建立风险量化模型分类和排序问题，将登录失败、邮箱验证链接失效、预约后 404、Dashboard 跳转异常等归为阻断类问题，将搜索不明显、内容过于专业、响应偏慢等归为体验类问题，支持团队聚焦关键失败点，后续通过AB测试优选界面方案。\n\n•  结合员工端调研识别 50%+ 员工在患者档案页浏览时感到困惑，提出角色化工作台、快捷入口和功能清晰化建议；同时参与 Risk & Issue / Governance Change 内容整理，提升方案可实施性。",
    "exp-3-t": "RallyVille 金融公司（澳洲） · 市场运营助理",
    "exp-3-d": "•   用户洞察与内容策划：\n参与金融科普账号内容策划与图文输出，带领四人团队以故事化表达降低金融内容理解门槛，主导“痛点化场景”设计，成功推出“实习小白勇闯金融公司”系列，带动浏览量与互动量增加30%。\n\n•  信息拆解与表达优化：\n面向金融小白用户拆解复杂金融术语，优化图文与短视频表达方式，提升专业内容的可读性与传播效果。\n\n•  前端引流与转化支持：\n负责部分前端引流，通过图文及短视频内容触达潜在客户并导入社群，为后续用户沉淀与转化提供前端流量支持；提前识别并解决潜在用户反馈问题，保障项目稳定推进。\n\n•  内容生产与协作推进：\n负责金融专家长视频剪辑与短视频包装，提炼核心观点制作约 1.5 分钟短视频；建立一周三更协作机制，使用甘特图拆解外汇专家视频生产任务，协调多角色完成任务节点，提升跨团队协作效率。",
    "exp-4-t": "雅诗兰黛 · 市场部实习生",
    "exp-4-d": "·  行业研究与竞品拆解：\n围绕美妆行业趋势、产品定位、价格体系、渠道布局及节日营销，对 10+ 国内外美妆品牌开展竞品分析，输出市场研究内容。\n\n·  用户洞察与消费分析：\n基于高端美妆消费人群特征、代际差异与购买路径搭建用户画像，分析 2000+ 反馈内容，并通过交叉数据分析， 分析不同客群的消费偏好与决策逻辑。\n\n·  数字营销策略研究：\n研究淘宝、抖音、小红书、微信小程序等电商与内容平台的流量分发、广告推荐及兴趣电商转化链路，提炼平台营销打法与优化建议。运用 SWOT 模型对抖音电商、微信小程序进行营销分析，了解平台新玩法，通过对平台成功营销案例拆解出当下用户偏好。\n\n·  项目产出与策略支持：\n独立完成用户画像、竞品分析、平台营销、小程序路径及 CRM 营销案例等 10+ 份研究文档，支持品牌数字营销与活动策划。",
    "exp-5-t": "上海电视台第一财经 · 大型活动部实习生",
    "exp-5-d": "•  参与并落地“中国最美村镇”评选活动的活动主题与方案、采编选题、资源梳理、合作媒体沟通等活动全流程策划，拉动 200+ 村镇，对接政府、企业等多家合作方，制定“需求确认-进度反馈-危机预警”标准化 SOP，提升沟通效率 30%。\n\n•  协助团队执行活动，明确分工，确保各环节无缝衔接；通过定期会议和进度跟踪，及时调整任务分配，保障活动顺利进行。\n\n•  建立风险预警机制，提前识别并解决潜在的流量波动和用户反馈问题，保障项目稳定推进。在活动执行过程中，快速应对突发技术故障等问题，保障活动顺利进行并获得客户高度认可。\n\n• 根据活动方案把控活动细节，协调活动场地、设备、人员等各方资源，确保活动顺利进行；整理客户资料，走访村镇，与客户保持持紧密联系，协同其他部门为其提供专业服务，活动执行 0 失误，获得客户高度认可。\n\n•  负责项目公众号运营、整理 500+ 村镇的资料并撰写成大众易读的介绍、定期更新活动信息及村镇介绍内容，累计发布 10+ 篇内容，获得 1w+ 阅读、300+ 评论，运营期间粉丝数量涨幅达 15%。",
    "c-welcome": "欢迎联系",
    "display-name": "宋宇轩",
    "skills": [
      { "title": "用户洞察与问题诊断", "desc": "能够从反馈、路径和实际场景中识别关键问题，判断哪些问题真正影响用户完成任务。\n\n例： 在老年视觉护理机构数字体验升级项目中，我梳理预约、登录、信息获取与后台协作流程，并结合问卷与员工反馈完成问题归因和优先级判断。" },
      { "title": "市场研究与竞品分析", "desc": "能够围绕行业趋势、用户需求、竞品策略、价格体系、渠道布局和营销动作开展研究，并提炼有价值的结论。\n\n例： 在雅诗兰黛市场部线上实习中，我独立完成用户画像、竞品分析、平台营销、小程序路径及 CRM 案例等研究文档。" },
      { "title": "内容策划与信息转译", "desc": "擅长将复杂、专业或零散的信息转化为更清晰、更易理解、更适合传播的内容表达。\n\n例： 我曾将金融专业内容转化为“小白向”图文和短视频，也独立负责项目公众号文章的改写、排版与发布。" },
      { "title": "项目推进与执行落地", "desc": "能够在信息繁杂、环节较多、多人协作的场景下推进任务，从前期准备到最终落地保持执行稳定性。\n\n例： 在第一财经参与“中国最美村镇”项目期间，我负责前期信息整理、公众号运营及线下活动执行支持，协助项目顺利推进。" },
      { "title": "跨团队协作与沟通衔接", "desc": "能够在不同角色、不同需求之间完成信息同步、任务衔接和执行配合，让事情更顺畅地往前推进。\n\n例： 无论是在内容团队推进周更、在线下活动中配合执行，还是在体验优化项目中整理 Risk & Issue / Governance Change 内容，我都持续锻炼跨角色协作能力。" },
      { "title": "AI协作与工作流搭建", "desc": "能够将 AI 工具真正应用到真实任务场景中，不只是单点使用工具，而是围绕信息整理、内容生成、页面搭建、问题排查和迭代优化，形成更高效的 AI 工作流。\n\n例： 我独立完成了个人求职网页从 0 到 1 的策划、设计与搭建，并借助 AI 完成工具选型、页面优化、功能整合与问题排查，也在日常项目中持续用 AI 提升学习、分析和输出效率。" },
      { "title": "责任感强-主动解决问题-适应变化快-无限进化", "desc": "我对工作有较强的责任感，面对任务时更习惯主动想办法推进。遇到不确定的问题，我会先去梳理信息、寻找路径、推动落地；面对新的环境、工具或工作方式，也能比较快进入状态并完成适应。\n\n我有一定的自主性和创造性，既愿意把事情稳稳做完，也愿意在过程中不断优化方法，把想法真正变成结果。" }
    ],
    "footer-words": ["主动", "创造", "高效执行", "拥抱变化", "团队协作", "目标导向"],
    "tarot-hint": "点击卡牌揭晓",
    "timeline-hint": "点击查看详情",
    "modal-back": "返回",
    "exp-link-btn": "相关文档点击查看",
    "contact-email": "邮箱",
    "contact-wechat": "微信",
    "contact-phone": "电话",
    "voice-welcome-text": "嘿，你好呀！我是宇轩。欢迎来到我的数字角落。这里记录了我的经历，并展示已落地的奇思妙想。很高兴在这里遇见你，快开启你的探索之旅吧！",
    "nav-portfolio": "作品集 — 2026",
    "resume-btn": "下载简历",
    "footer-stay-curious": "保持好奇",
    "call-incoming": "来电显示",
    "call-name": "宋宇轩"
  },
  en: {
    "nav-about": "INFO",
    "nav-edu": "EDUCATION",
    "nav-exp": "TIMELINE (W/ PORTFOLIO)",
    "nav-skills": "SKILLS & TRAITS",
    "nav-cta": "CONTACT",
    "hero-sub": "It’s me.",
    "hero-role": "User Insights × Creative Strategy × Digital UX Optimization Candidate",
    "hero-desc": "Hybrid background in user research, content planning, project execution, and market analysis. Experienced in digital experience optimization, marketing research, content dissemination, and event support, with the ability to integrate information, deconstruct problems, and output solutions across diverse scenarios.\nAdept at leveraging AI tools and data insights to transform complex information into clear, efficient user experiences and content expressions, bridging the gap between user needs, creative expression, and tangible delivery.",
    "edu-hku-major": "University of Sydney (Australia)",
    "edu-hku-desc": "The shift from 'doing projects' to 'understanding the problem itself' was my biggest growth during postgraduate studies. Through Project Management at USYD, I realized projects are structural deconstructions of complex problems. Cost, risk, and resource allocation are essentially relationships between data and decisions. I began introducing data analysis and model thinking: transforming 'intuition' into verifiable strategies via A/B testing in growth projects, and reconstructing user paths based on data in digital optimization. To me, AI is not just a toolkit, but a new way of problem-solving—understanding the world with data and approaching decisions with models.",
    "edu-cuhk-major": "SISU Yan'an College",
    "edu-cuhk-desc": "Undergraduate studies were more about establishing my underlying coordinates for understanding the business world. Starting from Exhibition and Tourism, I entered a broader business context. Whether planning an event or designing a travel route, it's about organizing and guiding 'people flow, information, and consumption decisions.' Systematic training in economics and management allowed me to understand these phenomena structurally: from supply-demand to user choice, many experience-based judgments could be deconstructed. I realized that many 'seemingly successful' executions lacked verifiable logic. I shifted from 'execution' to 'analysis': establishing data cognition through surveys and interviews, and deriving robust strategic directions from data. This established my core belief: the heart of business is not just connecting resources, but understanding human decision mechanisms in different contexts.",
    "edu-cert-btn": "Certificates",
    "exp-1-t": "AI Personal Site 0-1 · Planning & Building",
    "exp-1-d": " Background: During the job search process, I hoped to replace traditional static resumes with a more intuitive and interactive personal website to enhance my personal presentation and assist in more efficient communication with interviewers. At the same time, I also wanted to use this project to practice the application of AI tools in real scenarios.\n\n Task: My task was to use AI tools to independently complete the planning, design, and construction of a personal job search website from 0 to 1, and make this website not only carry personal information but also have more complete display and interaction functions.\n\n Action: During the project advancement process, I focused on tool selection, page design, content organization, document integration, and deployment exploration. By continuously comparing and selecting appropriate AI tools, I gradually completed the website structure construction and continuously optimized page performance and interaction methods. At the same time, I solved specific problems such as image uploading, document jumping, and external resource integration, finally integrating multiple display needs into the same webpage.\n\n Result: Finally, I independently completed a set of personal display webpages with functions such as Chinese and English switching, voice welcome, multi-version resume download, portfolio, and document jumping. This project not only improved my personal presentation effect but also systematically exercised my AI collaboration, fast learning, problem-solving, and product presentation abilities.",
    "exp-2-t": "Eye Hospital Site UX · Campus Project",
    "exp-2-d": "Project Overview:\nThis is a digital experience upgrade project for an elderly vision care institution. The goal is to identify key pain points affecting users around appointment, login, information acquisition, and internal collaboration processes, and propose feasible interface optimization plans through questionnaires, experience assessments, prototype design, and testing, thereby improving the efficiency and satisfaction of patients, families, and healthcare personnel.\n\nResponsibilities:\nSorted 4 key user journeys, including appointment, login, homepage information acquisition, and Dashboard/backend workstation. Identified core issues affecting task completion rates (high bounce rate and low registration conversion), and delivered optimization suggestions and prototype solutions.\n\n• Conducted problem attribution based on questionnaires, user feedback, and page flow walkthroughs. Identified that 28.6% of users encountered obstacles at the appointment entry, 20% were dissatisfied with system response speed, and 28.6% were unwilling to recommend the website, providing a basis for optimization priority.\n\n• Established a risk quantification model to classify and rank issues. Categorized login failure, invalid email verification link, 404 after appointment, and Dashboard jump exceptions as blocking issues. Categorized obscure search, overly professional content, and slow response as experience issues, supporting the team in focusing on critical failure points. Subsequently optimized interface plans through A/B testing.\n\n• Identified that 50%+ of staff felt confused when browsing patient profile pages based on staff-side research. Proposed role-based workstations, quick entries, and functional clarification. Participated in organizing Risk & Issue / Governance Change content to enhance plan feasibility.",
    "exp-3-t": "RallyVille Finance · Marketing Assistant",
    "exp-3-d": "• User Insights & Content Strategy:\nParticipated in content planning and graphic output for financial education accounts. Led a team of four to lower the barrier for financial content understanding through storytelling. Led the design of \"pain-point scenes,\" successfully launching the \"Intern Newbie's Financial Adventure\" series, driving a 30% increase in views and engagement.\n\n• Information Deconstruction & Expression Optimization:\nDeconstructed complex financial terms for financial novices, optimized graphic and short video expression, and improved the readability and dissemination effect of professional content.\n\n• Frontend Traffic & Conversion Support:\nResponsible for frontend traffic acquisition, reaching potential customers through graphic and short video content and importing them into communities to provide traffic support for user retention and conversion. Proactively identified and resolved potential user feedback issues to ensure stable project progress.\n\n• Content Production & Collaboration Promotion:\nResponsible for editing and packaging long videos for financial experts, extracting core viewpoints into ~1.5 minute short videos. Established a three-updates-per-week collaboration mechanism, used Gantt charts to deconstruct video production tasks for forex experts, and coordinated multiple roles to complete task nodes, enhancing cross-team collaboration efficiency.",
    "exp-4-t": "Estée Lauder · Marketing Intern",
    "exp-4-d": "· Industry Research & Competitor Analysis:\nConducted competitor analysis for 10+ domestic and international beauty brands focused on industry trends, product positioning, pricing systems, channel layout, and festival marketing, outputting market research reports.\n\n· User Insights & Consumption Analysis:\nBuilt user personas based on premium beauty consumer characteristics, generational differences, and purchase paths. Analyzed 2000+ feedback entries and used cross-data analysis to understand consumption preferences and decision logic across different customer segments.\n\n· Digital Marketing Strategy Research:\nStudied traffic distribution, ad recommendation, and interest-based e-commerce conversion paths on platforms like Taobao, Douyin, Xiaohongshu, and WeChat Mini Programs. Used SWOT models to analyze Douyin e-commerce and WeChat Mini Programs, extracting platform marketing tactics and optimization suggestions from successful cases.\n\n· Project Output & Strategic Support:\nIndependently completed 10+ research documents including user personas, competitor analysis, platform marketing, mini-program paths, and CRM marketing cases, supporting brand digital marketing and campaign planning.",
    "exp-5-t": "CBN TV · Events Dept Intern",
    "exp-5-d": "• Participated in and implemented the entire event planning process for the \"China's Most Beautiful Villages\" selection, including event themes/proposals, editorial selection, resource organization, and communication with partner media. Engaged 200+ villages, coordinated with government, enterprises, and other partners, and developed standardized SOPs for \"Requirement Confirmation - Progress Feedback - Crisis Warning,\" improving communication efficiency by 30%.\n\n• Assisted the team in event execution, clarifying labor division to ensure seamless connection between all stages. Adjusted task allocation timely through regular meetings and progress tracking to ensure smooth event operation.\n\n• Established a risk warning mechanism to proactively identify and resolve potential traffic fluctuations and user feedback issues, ensuring stable project progress. Rapidly responded to technical failures during execution, ensuring smooth event completion and receiving high client recognition.\n\n• Managed event details according to proposals, coordinating venues, equipment, personnel, and other resources. Organized client data and visited villages to maintain close relations, collaborating with other departments to provide professional services, achieving zero errors in execution.\n\n• Responsible for the project's official WeChat account, organizing data for 500+ villages and writing public-friendly introductions. Regularly updated event information and village features, published 10+ articles, achieving 10k+ reads and 300+ comments, with a 15% increase in followers during the operation period.",
    "c-welcome": "WELCOME",
    "display-name": "Yuxuan Song",
    "skills": [
      { "title": "User Insights & Diagnosis", "desc": "Ability to identify key issues from feedback and user journeys. Identify problems that truly impact task completion.\n\ne.g., In the vision care UX project, I sorted appointment/login flows and used feedback for root cause analysis." },
      { "title": "Market Research & Analysis", "desc": "Conduct research on industry trends, user needs, and competitor strategies to extract valuable conclusions.\n\ne.g., During the Estée Lauder internship, I independently completed persona, competitor analysis, and CRM research docs." },
      { "title": "Content Strategy & Translation", "desc": "Adept at transforming complex or professional information into clear, easily understandable content.\n\ne.g., Converted professional finance content into 'newbie-friendly' graphics/videos and managed official account articles." },
      { "title": "Project Execution & Delivery", "desc": "Drive tasks in complex, multi-person collaboration scenarios, maintaining execution stability from start to finish.\n\ne.g., During the 'Most Beautiful Villages' project, I managed data organization and event support to ensure smooth progress." },
      { "title": "Cross-team Collaboration", "desc": "Synchronize information and coordinate execution between different roles and requirements to drive progress.\n\ne.g., Coordinated weekly updates in content teams and handled Risk & Issue tracking in UX optimization projects." },
      { "title": "AI Collaboration & Workflows", "desc": "Apply AI tools to real-world tasks, creating efficient workflows for content generation and technical iteration.\n\ne.g., Built this personal site from 0-1 using AI for tool selection, page optimization, and feature integration." },
      { "title": "Responsible & Proactive · Agile & Learning · Infinite Evolution", "desc": "I have a strong sense of responsibility and prefer to proactively drive tasks forward. When facing uncertainties, I focus on gathering information, identifying paths, and delivery. I adapt quickly to new environments, tools, or workflows.\n\nWith moderate autonomy and creativity, I am committed to completing tasks reliably while continuously optimizing methods to turn ideas into tangible results." }
    ],
    "footer-words": ["Proactive", "Creative", "Efficient", "Adaptable", "Teamwork", "Goal-oriented"],
    "tarot-hint": "Click card to unveil",
    "timeline-hint": "Click to View Details",
    "modal-back": "Back",
    "exp-link-btn": "View Related Docs",
    "contact-email": "Email",
    "contact-wechat": "WeChat",
    "contact-phone": "Phone",
    "voice-welcome-text": "Hey there! I'm Yuxuan. Welcome to my digital corner. My experiences and realized ideas are documented here. So glad to meet you here, now let's start the journey!",
    "nav-portfolio": "Portfolio — 2026",
    "resume-btn": "Download Resume",
    "footer-stay-curious": "Stay Curious",
    "call-incoming": "Incoming Call",
    "call-name": "Yuxuan Song"
  }
};

export const IMAGES = {
  main: "https://raw.githubusercontent.com/yson3892/Ai-/main/39ac3817800d2b5d57b35e8c11e1da6b.jpg", // Vertical 1 (Main)
  v1: "https://picsum.photos/seed/yuxuan-v1/800/1200",
  v2: "https://raw.githubusercontent.com/yson3892/Ai-/main/WechatIMG355.jpg", // Vertical 2
  h1: "https://raw.githubusercontent.com/yson3892/Ai-/main/165c26762bca407d111eec72f37028f1.jpg", // Horizontal 1
  h2: "https://raw.githubusercontent.com/yson3892/Ai-/main/b3e17d404063f43992fd6e4e479054d7.jpg", // Horizontal 2
  hku: "https://raw.githubusercontent.com/yson3892/Ai-/main/6beaec72832d8d2f99bf4e9c22c30b3a.jpg",
  cuhk: "https://raw.githubusercontent.com/yson3892/Ai-/main/39956ee85c8b24909da451f7b739bedf.jpg",
  memoji: "https://raw.githubusercontent.com/yson3892/Ai-/main/602f2a7c8b3c81886cb03b2e237aabe1.jpg", // Image 5: Memoji
  exp1: "https://raw.githubusercontent.com/yson3892/Ai-/main/%E6%88%AA%E5%B1%8F2026-04-16%2021.55.25.png",
  exp2: "https://raw.githubusercontent.com/yson3892/Ai-/main/%E6%88%AA%E5%B1%8F2026-04-16%2022.16.08.png",
  exp3: "https://raw.githubusercontent.com/yson3892/Ai-/main/%E6%88%AA%E5%B1%8F2026-04-16%2022.01.27.png",
  exp4: "https://raw.githubusercontent.com/yson3892/Ai-/main/%E9%9B%85%E8%AF%97%E5%85%B0%E9%BB%9B.png",
  exp5: "https://raw.githubusercontent.com/yson3892/Ai-/main/b82fa32f61bfef67e0261cd25fe0ff28.jpg",
  cert: "https://raw.githubusercontent.com/yson3892/Ai-/main/%E6%88%AA%E5%B1%8F2026-04-17%2001.35.59.png"
};
